### ISSUE TITLE
Current progress with your library 

### ISSUE THREAD

**Issue by ElvargThemSelf** [casept/psxgs#1]
You said that TMD rendering isn't properly implemented yet, so I'm curious to know the current progress with psxgs library. And is this library based on an existing decompilation or is this a complete rewrite from scratch?

**Comment by casept** [comment]
It's been over a year since I've last touched the project, so I don't quite remember how far along it is. I think I remember struggling with camera-related functionality before giving up, but I'm not sure.

No decompilation was used, but I did look at Sony's library documentation and sample program sources from the official SDK to figure out the official API.

Generally speaking, I don't have the time or energy right now to work much on the project (if at all). Feel free to take over if you're interested.

**Comment by ElvargThemSelf** [comment]
Sure, I might be willing to complete where you've left off and might as well take full ownership of this repo since there seems to be nobody willing to do the work.
